
[functions.create-checkout]
enabled = true
verify_jwt = false
import_map = "./functions/create-checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-checkout/*.html" ]

[functions.dodo-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/dodo-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/dodo-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/dodo-webhook/*.html" ]

[functions.generate-thumbnail]
enabled = true
verify_jwt = false
import_map = "./functions/generate-thumbnail/deno.json"
entrypoint = "./functions/generate-thumbnail/index.ts"

[functions.cancel-subscription]
enabled = true
verify_jwt = false
import_map = "./functions/cancel-subscription/deno.json"
entrypoint = "./functions/cancel-subscription/index.ts"

[functions.unlink-google]
enabled = true
verify_jwt = true
entrypoint = "./functions/unlink-google/index.ts"
